name: Convert jupytext to .ipynb

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  convert:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/catthehacker/ubuntu:act-latest
    services:
      lakefs:
        image: treeverse/lakefs:1.3.1
        ports:
          - 8000:8000
        env:
          LAKEFS_INSTALLATION_USER_NAME: "quickstart"
          LAKEFS_INSTALLATION_ACCESS_KEY_ID: "AKIAIOSFOLQUICKSTART"
          LAKEFS_INSTALLATION_SECRET_ACCESS_KEY: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
          LAKEFS_DATABASE_TYPE: "local"
          LAKEFS_AUTH_ENCRYPT_SECRET_KEY: "THIS_MUST_BE_CHANGED_IN_PRODUCTION"
          LAKEFS_BLOCKSTORE_TYPE: "local"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
      - name: Convert to notebook
        run: |
          jupytext --to notebook data_versioning_best_practices.py
          nbstripout data_versioning_best_practices.ipynb
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Convert Jupytext
